# Generated by Django 3.0.6 on 2020-08-11 01:41

import codewithtm.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('image_path', models.TextField(blank=True, null=True)),
                ('article', models.TextField(validators=[codewithtm.validators.validate_content])),
                ('summary', models.TextField(validators=[codewithtm.validators.validate_content])),
                ('read_time', models.IntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Out Dated', 'Out Dated')], max_length=20)),
                ('published_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to='authors.Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
            ],
            options={
                'ordering': ['order', '-timestamp'],
                'unique_together': {('slug', 'category')},
            },
        ),
    ]
