# Generated by Django 3.0.6 on 2020-07-01 03:23

import codewithtm.validators
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('slug', models.SlugField(max_length=90, unique=True)),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=posts.models.upload_post_image, width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('article', models.TextField(validators=[codewithtm.validators.validate_content])),
                ('summary', models.TextField(validators=[codewithtm.validators.validate_content])),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Out Dated', 'Out Dated')], max_length=20)),
                ('published_date', models.DateField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_posts', to='authors.Author')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_posts', to='categories.Category')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
