# Generated by Django 3.0.6 on 2020-07-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200706_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
