# Generated by Django 3.0.6 on 2020-07-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200705_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analytic',
            old_name='count',
            new_name='view_count',
        ),
    ]
