# Generated by Django 3.0.6 on 2020-07-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20200705_1219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analytic',
            options={'ordering': ['-view_count'], 'verbose_name': 'Analytics', 'verbose_name_plural': 'Analytics'},
        ),
    ]
