# Generated by Django 3.0.6 on 2020-08-22 14:04

import codewithtm.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20200819_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(validators=[codewithtm.validators.validate_content]),
        ),
    ]
