# Generated by Django 3.0.6 on 2020-09-15 21:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_auto_20200915_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingpreference',
            name='user',
        ),
        migrations.AddField(
            model_name='marketingpreference',
            name='email',
            field=models.EmailField(default=datetime.datetime(2020, 9, 15, 21, 23, 21, 581300, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
