# Generated by Django 3.0.6 on 2020-07-01 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='ip_address',
        ),
    ]
