# Generated by Django 3.0.6 on 2020-07-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_remove_like_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
