# Generated by Django 3.0.6 on 2020-07-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_remove_like_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
    ]
