# Generated by Django 3.0.6 on 2020-07-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_auto_20200701_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Like', 'verbose_name_plural': 'Like'},
        ),
    ]
